spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 604800000  # 7 days

  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
      url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

logging:
  level:
    com.stjoseph: DEBUG
